site_name: ANPR Documentatie
site_url: https://ida-birdseeye.github.io/anpr-visualisaties/

plugins:
  - search
  - macros:
      include_dir: data

nav:
  - Inleiding: 01_inleiding.md
  - Aanpak: 02_aanpak.md
  - Functionele eisen: 03_functionele_eisen.md
  - Visualisaties:
      - Overzicht: 04_visualisaties.md
      - 4.1 Uurgemiddeldes per camera locatie: 04_visualisaties/4.1_uurgemiddeldes_per_camera_locatie.md
      - 4.2 Tijdvak analyse: 04_visualisaties/4.2_tijdvak_analyse.md
      - 4.3 Venstertijden analyse: 04_visualisaties/4.3_venstertijden_analyse.md
      - 4.4 Herkomst voertuigen: 04_visualisaties/4.4_herkomst_voertuigen.md
      - 4.5 Bezoekersgedrag – herkomst: 04_visualisaties/4.5_bezoekersgedrag_herkomst.md
      - 4.6 Bezoekersgedrag – SBI: 04_visualisaties/4.6_bezoekersgedrag_sbi.md
      - 4.7 Bezoekersgedrag – bedrijfsgrootte: 04_visualisaties/4.7_bezoekersgedrag_bedrijfsgrootte.md
      - 4.8 Kruisverbanden: 04_visualisaties/4.8_kruisverbanden.md
      - 4.9 Overzichtsstatistieken: 04_visualisaties/4.9_overzichtsstatistieken.md
      - 4.12 Camera metadata en zone polygonen: 04_visualisaties/4.12_camera_metadata_en_zone_polygonen.md
  - Conclusie: 06_conclusie.md
  - Aanbevelingen: 07_aanbevelingen.md
  - Referenties: 08_referenties.md
